language: php
php:
  - 5.3
  - 5.4
script: "sh -c 'cd tests && php all_tests.php'"
notifications:
  recipients:
    - alessandro.fazzi@welaika.com
    - fabrizio.monti@welaika.com
    - federico.parodi@welaika.com
    - filippo.gangidino@welaika.com
    - matteo.piotto@welaika.com
